apiVersion: v1
kind: Pod
metadata:
  name: tidb
  labels:
    env: test
    app: tidb
spec:
  containers:
  - name: tidb
    image: pingcap/tidb:v5.3.0
---
apiVersion: v1
kind: Pod
metadata:
  name: billing
  labels:
    env: test
    app: billing
spec:
  containers:
  - name: mysql-cli
    image: alpine:3.14
    command: ["tail", "-f", "/dev/null"]
---
apiVersion: v1
kind: Pod
metadata:
  name: website
  labels:
    env: test
    app: website
spec:
  containers:
  - name: mysql-cli
    image: alpine:3.14
    command: ["tail", "-f", "/dev/null"]
