apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "tidb-demo"
spec:
  description: "tidb demo policy"
  endpointSelector:
    matchLabels:
      app: tidb
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: client
      toPorts:
        - ports:
            - port: "4000"
              protocol: TCP
          rules:
            l7proto: tidbsql
            l7:
              - key: "select"
                value: "mydb.t1"
              - key: "insert"
                value: "mydb.t1"
              - key: "update"
                value: "mydb.t1"
              - key: "delete"
                value: "mydb.t1"
