apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "tidb-security"
spec:
  description: "Enhance TiDB security"
  endpointSelector:
    matchLabels:
      env: test
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: website
      toPorts:
        - ports:
            - port: "4000"
              protocol: TCP
          rules:
            l7proto: tidbsql
            l7:
              - select: "test.web.*"
              - insert: "test.web.*"
              - update: "test.web.*"
              - delete: "test.web.*"
    - fromEndpoints:
        - matchLabels:
            app: billing
      toPorts:
        - ports:
            - port: "4000"
              protocol: TCP
          rules:
            l7proto: tidbsql
            l7:
              - select: "test.billing.*"
              - insert: "test.billing.*"
              - update: "test.billing.*"
              - delete: "test.billing.*"
