name: test-build

on:
  push:
    branches:
      - handlerww/tidb-filter


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: registry.cn-heyuan.aliyuncs.com
          username: ${{ secrets.ALI_DOCKER_USERNAME }}
          password: ${{ secrets.ALI_DOCKER_PASSWORD }}
      - run: |
          DOCKER_DEV_ACCOUNT=registry.cn-heyuan.aliyuncs.com/handlerww/cilium-dev DOCKER_IMAGE_TAG=latest make dev-docker-image 
          docker push registry.cn-heyuan.aliyuncs.com/handlerww/cilium-dev:latest